# Generated by Django 2.2.2 on 2019-06-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0002_auto_20190608_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
