# Generated by Django 2.2.2 on 2019-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0002_auto_20190610_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='value',
            field=models.SmallIntegerField(choices=[(0, 'Draw'), (1, 'Home'), (2, 'Away')], default=0, verbose_name='outcome'),
        ),
    ]
