# Generated by Django 2.2.2 on 2019-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0006_auto_20190612_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='due',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
