# Generated by Django 2.2.3 on 2019-07-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0007_auto_20190617_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='value',
        ),
        migrations.RemoveField(
            model_name='game',
            name='result',
        ),
        migrations.AddField(
            model_name='bet',
            name='away_guess',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='home_guess',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='away_goals',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_goals',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
