# Generated by Django 2.2.3 on 2019-07-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0010_stringanswer_stringquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
