# Generated by Django 2.2.3 on 2019-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0011_stringquestion_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='changed',
            new_name='changes',
        ),
        migrations.RenameField(
            model_name='stringquestion',
            old_name='changed',
            new_name='changes',
        ),
        migrations.AddField(
            model_name='bet',
            name='changed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stringanswer',
            name='changed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
