# Generated by Django 2.2.3 on 2019-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0013_numericanswer_numericquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericanswer',
            name='answer',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='numericquestion',
            name='correct_answer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
