# Generated by Django 2.2.3 on 2019-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0014_auto_20190719_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='mult4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='mult4left',
            field=models.SmallIntegerField(default=3),
        ),
    ]
