# Generated by Django 2.2.3 on 2019-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0015_auto_20190727_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='double_team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
