# Generated by Django 2.2.3 on 2019-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0017_game_matchday'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='survivor_died',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='score',
            name='survivor_fails',
            field=models.SmallIntegerField(default=0),
        ),
    ]
