# Generated by Django 2.2.3 on 2019-07-27 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tippelde', '0019_auto_20190727_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivorRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('award', models.PositiveSmallIntegerField(default=10)),
                ('changes', models.PositiveSmallIntegerField(default=0)),
                ('penalty', models.PositiveSmallIntegerField(default=3)),
                ('evaluated', models.BooleanField(default=False)),
                ('matchday', models.PositiveSmallIntegerField(unique=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tippelde.Tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurvivorGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.PositiveSmallIntegerField(default=0)),
                ('answer', models.CharField(max_length=200)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tippelde.StringQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
