# Generated by Django 2.2.3 on 2019-07-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0020_survivorguess_survivorround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivorguess',
            name='round',
        ),
        migrations.AddField(
            model_name='survivorguess',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tippelde.SurvivorRound'),
            preserve_default=False,
        ),
    ]
