# Generated by Django 2.2.3 on 2019-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0021_auto_20190727_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivorround',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
