# Generated by Django 2.2.2 on 2019-06-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippelde', '0003_auto_20190608_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
